### ISSUE TITLE
Arm64 but got Arm

### ISSUE THREAD

**Issue by xyxdaily** [iofomo/abyss#1]
/library/src/main/jni/CMakeLists.txt

![image](https://github.com/user-attachments/assets/beb60926-18f1-4def-9605-e1fe7418f3f1)

# 检测目标架构
if(CMAKE_SYSTEM_PROCESSOR STREQUAL "aarch64")
   message(STATUS "Target architecture is ARM64")
   set(CMAKE_ANDROID_ARCH_ABI "arm64-v8a")
elseif(CMAKE_SYSTEM_PROCESSOR STREQUAL "armv7l")
   message(STATUS "Target architecture is ARM32")
   set(CMAKE_ANDROID_ARCH_ABI "armeabi-v7a")
else()
   message(STATUS "Target architecture is not ARM")
endif()

**Comment by iofomo** [comment]
3Q
